git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  authors:
    email: contact@syrtis.ai
    name: weeger
  name: php_semantic_schema_web
  vendor: syrtis
  version: 0.0.20
wex:
  migration: 1
  version: 6.0.112
